<?php

namespace AppBundle\Repository;

/**
 * ActualiteImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteImageRepository extends \Doctrine\ORM\EntityRepository
{
}
