<?php

namespace AppBundle\Repository;

/**
 * actualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class actualiteRepository extends \Doctrine\ORM\EntityRepository
{
}
