<?php

namespace AppBundle\Repository;

/**
 * contactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contactRepository extends \Doctrine\ORM\EntityRepository
{
}
