<?php

namespace AppBundle\Repository;

/**
 * gamificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class gamificationRepository extends \Doctrine\ORM\EntityRepository
{
}
