<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MarkersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllMarkers(){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT * FROM AppBundle:Markers '
            )
            ->getResult();
    }
}
