<?php

namespace AppBundle\Repository;

/**
 * newsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class newsletterRepository extends \Doctrine\ORM\EntityRepository
{
}
