<?php

namespace AppBundle\Repository;

/**
 * ObservationImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationImageRepository extends \Doctrine\ORM\EntityRepository
{
}
