<?php

namespace AppBundle\Repository;


use AppBundle\Entity\Observation;
use Doctrine\ORM\EntityRepository;

/**
 * ObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObservationRepository extends EntityRepository
{
    public function getObservationsByFamily($famille){
        return $this
            ->createQueryBuilder('o')
            ->leftJoin('o.taxref', 'taxref')
            ->where('o.observationStatus = :status')
            ->andWhere('taxref.famille = :famille')
            ->setParameter('status', Observation::STATUS_VALIDATE)
            ->setParameter('famille', $famille)
            ->getQuery()
            ->getResult()
        ;
    }
}

