<?php

namespace AppBundle\Repository;

/**
 * observationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class observationRepository extends \Doctrine\ORM\EntityRepository
{
}
