<?php

namespace AppBundle\Repository;

/**
 * taxrefFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taxrefFileRepository extends \Doctrine\ORM\EntityRepository
{
}
