<?php

namespace AppBundle\Repository;

/**
 * taxrefLienFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefLienFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastFile()
    {
        $query = $this->createQueryBuilder('t')
            ->orderBy('t.uploadedAt', 'DESC')
            ->setFirstResult(0)
            ->setMaxResults(1)
        ;

        return $query->getQuery()->getResult();
    }
}
