<?php

namespace AppBundle\Repository;

/**
 * TaxrefFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefFileRepository extends \Doctrine\ORM\EntityRepository
{
}
