<?php

namespace AppBundle\Repository;

/**
 * taxrefLienFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taxrefLienFileRepository extends \Doctrine\ORM\EntityRepository
{
}
