<?php

namespace AppBundle\Repository;

/**
 * taxrefLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefLienRepository extends \Doctrine\ORM\EntityRepository
{


}
