<?php

namespace AppBundle\Repository;

/**
 * taxrefLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taxrefLienRepository extends \Doctrine\ORM\EntityRepository
{
}
