<?php

namespace AppBundle\Repository;

/**
 * TaxrefLienFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxrefLienFileRepository extends \Doctrine\ORM\EntityRepository
{
}
