<?php

namespace AppBundle\Repository;

/**
 * taxrefRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taxrefRepository extends \Doctrine\ORM\EntityRepository
{
}
