# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    app_user.registration_listener:
        class : AppBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }


    app_user.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: appbundle_user_registration}