# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    images_directory: '%kernel.project_dir%/web/uploads/images'

services:

    app_user.registration_listener:
        class : AppBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }